### ISSUE TITLE
Wrong package relationship

### ISSUE THREAD

**Issue by guanmingwu** [reactome-idg/gwt-cytoscape-js#1]
The following code should not import a class in other package since the current package is called util, which is used as one of base packages for others. Also I don't know why you need this JsFactory class at all. Probably just delete it and place the constants to where they are used.

https://github.com/reactome-idg/gwt-cytoscape-js/blob/1e154e8a62140db49e3cbb39cb39a9da370f37a6/src/main/java/org/reactome/web/gwtCytoscapeJs/util/Console.java#L3

**Comment by TJBrunson** [comment]
This was set up to mirror how the test EventBus was made for the diagram class. You are right that it is not necessary. I have resolved this issue with my latest push
